version: '3'

services:
  nginx: 
    build:
      context: ./nginx    
    ports:
    - 4200:80

  api: 
    build:
      context: ./backend    
    volumes:
      - /node_modules
      - ./backend:/app
    ports:
    - 3000:3000

  client: 
    build:
      context: ./client
    volumes:
      - /node_modules
      - ./client:/app
   